name: Build and Upload Artifact

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Run Maven build
      - name: Build with Maven
        run: mvn clean install


      # Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-libs
          path: target/*
          
      - name: Make release
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "zShop release"
          automatic_release_tag: "latest"
          files: target/*
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false          
